### ISSUE TITLE
badMIXTURE R command question

### ISSUE THREAD

**Issue by flameseahorse** [danjlawson/mixChecker#1]
Hi, 

I'm trying to draw residual plots using badMIXTURE.

First, I ran the example (./convert.sh) following https://github.com/danjlawson/badMIXTUREexample
So, I have files "Recent_admix_cp_pop_linked.chunklengths.out" and Recent_admix.11.P and Q and other many files..

Using these files, how can i draw the residual plot in R?
I'm trying to "compareMixtureToData" in badMIXTURE using following command line.

mix <- read.table("../badMIXTUREexample/Recent_admix.11.P")
dataraw <- read.table("./Recent_admix_cp_pop_linked.chunkcounts.out")
ids <- read.table("./Recent_admix.ids")
adm <- compareMixtureToData(mix, dataraw, ids)

but, error is occur..
Error in rowSums(tdat) : 'x' must be numeric

Please, some advice for me.
Thanks.

**Comment by danjlawson** [comment]
This was a data formatting error; dataraw has row names, a header, and a line containing finestructure's "C factor", so it was read as a character matrix. Either use:

read.table("./Recent_admix_cp_pop_linked.chunkcounts.out"**,row.names=1,header=T**)

(R correctly skips the C factor line because it starts with a comment, but you may also want "skip=1")

or

readChunkcounts("./Recent_admix_cp_pop_linked.chunkcounts.out")

I have updated the function "compareMixtureToData" to provide helpful feedback if one or more of the input files are not as expected. 

Apologies for not spotting this comment sooner, it ended in my spam folder. I think that shouldn't happen any more.
